// Code generated by templ - DO NOT EDIT.

// templ: version: 0.2.432
package contact

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Contact() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"absolute bottom-20 left-[4.2rem] flex flex-col items-center gap-6\"><a href=\"\"><img src=\"/static/images/github-mark-white.svg\" class=\"w-6 h-6 opacity-40 hover:opacity-100 transition-all\"></a> <a href=\"\"><img src=\"/static/images/linkedin.svg\" class=\"w-6 h-6 opacity-40 hover:opacity-100 transition-all\"></a> <a href=\"\"><img src=\"/static/images/telegram.svg\" class=\"w-6 h-6 opacity-40 hover:opacity-100 transition-all\"></a></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
